### PR TITLE
styling table in dark mode

### PR DESCRIPTION
**Pull request by goldipl**

### CODE REVIEW

**Comment by danon** [comment]
@goldipl Please add the ruleset in `_dark_markdown.scss`.

**Comment by danon** [comment]
Borders are still not correct.

`table td` in `_tables.scss` has hardcoded color. Override `border-top-color` with `#2f2f2f` in `_dark_markdown.scss`.

**Comment by goldipl** [comment]
Table borders colors changed to: #2f2f2f

**Comment by danon** [comment]
Can you revert your changes from `_dark_topic.scss`, now that there are no changes there?

**Comment by goldipl** [comment]
@danon Done :)

**Comment by danon** [comment]
The change is deployed on https://4programmers.dev/. 

It's an opporutnity to check if the desired behaviour is reproduced.

**Comment by danon** [comment]
The change is deployed to production.

**Pull request merged**
